# Generated by Django 3.0.8 on 2020-07-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='addressc',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
