# Generated by Django 3.0.8 on 2020-08-03 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_food_name3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coding',
            fields=[
                ('text', models.CharField(max_length=10)),
                ('gender', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(unique=True)),
                ('Gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Coding')),
            ],
        ),
    ]
