# Generated by Django 3.0.8 on 2020-08-03 06:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_coding_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=None, max_length=20)),
                ('name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=None, max_length=20)),
                ('serial', models.CharField(default=None, max_length=50)),
                ('cotter_number', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=None, max_length=20)),
                ('name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sinter_process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=None, max_length=20)),
                ('transfer_doc_id', models.CharField(default=None, max_length=50)),
                ('stage_id', models.CharField(default=None, max_length=50)),
                ('layer', models.CharField(default=None, max_length=50)),
                ('a', models.CharField(default=None, max_length=50)),
                ('b', models.CharField(default=None, max_length=50)),
                ('cheak_emplotee_id', models.CharField(default=None, max_length=50)),
                ('check_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='檢查時間')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='pwd',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='serial',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.CreateModel(
            name='Transfer_doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=None, max_length=20)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customers')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
        ),
    ]
