# Generated by Django 3.0.8 on 2020-08-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200803_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='number',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='客戶的表'),
        ),
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='產品的表'),
        ),
    ]
