# Generated by Django 3.0.8 on 2020-08-03 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200803_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinter_process',
            name='cheak_emplotee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employee'),
        ),
        migrations.AlterField(
            model_name='sinter_process',
            name='transfer_doc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Transfer_doc'),
        ),
    ]
