# Generated by Django 3.0.8 on 2020-08-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200803_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer_doc',
            name='number',
            field=models.CharField(max_length=20, verbose_name='移轉單的表'),
        ),
    ]
