# Generated by Django 3.0.8 on 2020-08-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200803_1440'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.RemoveField(
            model_name='list',
            name='Gender',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.AlterField(
            model_name='transfer_doc',
            name='number',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='移轉單的表'),
        ),
        migrations.DeleteModel(
            name='Coding',
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
