# Generated by Django 3.0.8 on 2020-08-03 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200803_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='number',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='number',
            field=models.CharField(max_length=20, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='number',
            field=models.CharField(max_length=20, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='sinter_process',
            name='check_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='check_time'),
        ),
        migrations.AlterField(
            model_name='sinter_process',
            name='number',
            field=models.CharField(max_length=20, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='transfer_doc',
            name='number',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='id'),
        ),
    ]
