# Generated by Django 3.0.8 on 2020-08-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200803_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinter_process',
            name='transfer_doc_id',
            field=models.CharField(choices=[('a', 'first'), ('b', 'second'), ('c', 'third')], default='1', max_length=20),
        ),
    ]
