# Generated by Django 3.0.8 on 2020-08-03 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200803_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinter_process',
            name='stage_id',
            field=models.CharField(choices=[('EARLY', 'EARLY'), ('MIDDIE', 'second'), ('EARLY', 'EARLY')], default='EARLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='sinter_process',
            name='transfer_doc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Transfer_doc'),
        ),
    ]
